language: python

python:
    - '3.6'
    - '3.5'
    - '3.4'
    - '3.3'
    - '2.7'
    - '2.6'

install:
    - 'pip install .'
    - 'pip install --upgrade "pytest>=3.0.0"'

script:
    - 'py.test'
